import { contentBundleSchema, validateContentBundle } from "@/content/validator";
import type { ContentBundle } from "@/content/validator";
import { createInitialEngineState, stepCaseEngine } from "@/domain/engine";
import type { CaseEngineState } from "@/domain/engine";

export interface Case001Session {
  readonly content: ContentBundle;
  readonly initialState: CaseEngineState;
}

export const CASE_001_SLOT_ID = "slot_case_001";
export const CASE_001_MAIL_CHANNEL_ID = "channel_001_mail";
export const CASE_001_MESSENGER_CHANNEL_ID = "channel_001_messenger";

export function loadCase001Session(): Case001Session {
  const parsed = contentBundleSchema.parse({
    case: {
      id: "case_001_missing_signal",
      version: "1.0.0",
      title: "Missing Signal",
      subtitle: "A Pelaga Systems engineer has vanished.",
      estimatedMinutes: 30,
      entryStageId: "stage_001_missing_engineer",
      stages: [],
      entities: [],
      objectives: [
        {
          id: "obj_001_verify_location",
          title: "Verify Maya Pranata's final confirmed location",
          description:
            "Two records describe Maya's location on the same night. Determine which account is consistent with the evidence.",
          optional: false,
          startRule: { always: true },
          completionRule: {
            all: [{ entityDiscovered: "ev_001_ferry_departure" }, { entityDiscovered: "ev_001_emergency_call" }],
          },
          hintIds: ["hint_001_verify_location_1"],
          nextObjectiveIds: [],
        },
      ],
      triggers: [
        {
          id: "trigger_001_bootstrap",
          once: true,
          priority: 100,
          rule: { eventOccurred: { type: "case_001_bootstrap" } },
          effects: [
            { type: "start_objective", objectiveId: "obj_001_verify_location" },
            { type: "unlock_application", applicationId: "app_mail" },
            { type: "unlock_application", applicationId: "app_messenger" },
            { type: "unlock_application", applicationId: "app_records" },
            { type: "unlock_application", applicationId: "app_evidence_board" },
            { type: "unlock_application", applicationId: "app_objectives" },
            { type: "queue_dialogue", nodeId: "dialogue_001_sera_intro" },
          ],
        },
        {
          id: "trigger_001_ferry_discovery",
          once: true,
          priority: 50,
          rule: { eventOccurred: { type: "record_opened", entityId: "rec_001_ferry_departure" } },
          effects: [{ type: "discover_evidence", evidenceId: "ev_001_ferry_departure" }],
        },
        {
          id: "trigger_001_emergency_discovery",
          once: true,
          priority: 50,
          rule: { eventOccurred: { type: "record_opened", entityId: "rec_001_emergency_call" } },
          effects: [{ type: "discover_evidence", evidenceId: "ev_001_emergency_call" }],
        },
        {
          id: "trigger_001_objective_complete",
          once: true,
          priority: 10,
          rule: { all: [{ entityDiscovered: "ev_001_ferry_departure" }, { entityDiscovered: "ev_001_emergency_call" }] },
          effects: [{ type: "complete_objective", objectiveId: "obj_001_verify_location" }],
        },
      ],
      outcomes: [
        {
          id: "outcome_001_stage1",
          title: "Stage 1 verification complete",
          priority: 1,
          endingContentId: "ending_001_stage1",
          evaluationRule: { objectiveCompleted: "obj_001_verify_location" },
          effects: [],
        },
      ],
      searchableIndex: [
        {
          entityId: "rec_001_ferry_departure",
          entityType: "record",
          title: "Ferry Departure Record",
          exactTerms: ["ferry", "departure", "ferry departure"],
          aliases: ["ferry record", "transit record"],
          partialTerms: ["ferry", "departure"],
          unavailableBehavior: "hidden",
          availabilityRule: { always: true },
          authoredRank: 10,
        },
        {
          entityId: "rec_001_emergency_call",
          entityType: "record",
          title: "North Barrier Emergency Call",
          exactTerms: ["emergency", "emergency call", "north barrier"],
          aliases: ["emergency call metadata", "north barrier call"],
          partialTerms: ["emergency", "north barrier"],
          unavailableBehavior: "hidden",
          availabilityRule: { always: true },
          authoredRank: 9,
        },
        {
          entityId: "rec_001_maya_profile",
          entityType: "record",
          title: "Maya Pranata — Employee Profile",
          exactTerms: ["maya", "maya pranata", "employee profile"],
          aliases: ["maya profile", "employee record"],
          partialTerms: ["maya", "pranata"],
          unavailableBehavior: "hidden",
          availabilityRule: { always: true },
          authoredRank: 8,
        },
        {
          entityId: "rec_001_sera_field_note",
          entityType: "record",
          title: "CIAB Field Note — Sera Wibawa",
          exactTerms: ["sera", "sera wibawa", "field note"],
          aliases: ["sera note", "ciab field note"],
          partialTerms: ["sera", "wibawa"],
          unavailableBehavior: "hidden",
          availabilityRule: { always: true },
          authoredRank: 7,
        },
        {
          entityId: "char_maya_pranata",
          entityType: "character",
          title: "Maya Pranata",
          exactTerms: ["maya", "maya pranata"],
          aliases: [],
          partialTerms: ["maya", "pranata"],
          unavailableBehavior: "hidden",
          availabilityRule: { always: true },
          authoredRank: 6,
        },
        {
          entityId: "char_sera_wibawa",
          entityType: "character",
          title: "Sera Wibawa",
          exactTerms: ["sera", "sera wibawa"],
          aliases: [],
          partialTerms: ["sera", "wibawa"],
          unavailableBehavior: "hidden",
          availabilityRule: { always: true },
          authoredRank: 5,
        },
      ],
      assetBundleId: "bundle_001_missing_signal",
    },
    characters: [
      {
        id: "char_maya_pranata",
        displayName: "Maya Pranata",
        aliases: ["maya"],
        role: "Senior Systems Engineer, Pelaga Systems",
        organizationIds: [],
        publicProfile: {},
        portraitAssetId: "asset_maya_portrait",
        searchTerms: ["maya", "maya pranata", "engineer"],
        knownEvidenceIds: ["ev_001_ferry_departure", "ev_001_emergency_call"],
      },
      {
        id: "char_sera_wibawa",
        displayName: "Sera Wibawa",
        aliases: ["sera"],
        role: "CIAB Field Investigator",
        organizationIds: [],
        publicProfile: {},
        portraitAssetId: "asset_sera_portrait",
        searchTerms: ["sera", "sera wibawa", "investigator"],
        knownEvidenceIds: [],
      },
    ],
    records: [
      {
        id: "rec_001_ferry_departure",
        caseId: "case_001_missing_signal",
        recordType: "transit_record",
        title: "Ferry Departure Record",
        body: {},
        source: { system: "ferry_archive" },
        createdAt: "2041-11-18T22:14:00+07:00",
        relatedEntityIds: ["char_maya_pranata"],
        searchTerms: ["ferry", "departure", "ferry departure", "transit"],
        aliases: [],
        availabilityRule: { always: true },
        evidenceId: "ev_001_ferry_departure",
        metadata: { departure_time: "22:14", date: "2041-11-18", gate: "Meridian Ferry Gate" },
      },
      {
        id: "rec_001_emergency_call",
        caseId: "case_001_missing_signal",
        recordType: "emergency_log",
        title: "North Barrier Emergency Call",
        body: {},
        source: { system: "emergency_dispatch" },
        createdAt: "2041-11-18T22:31:00+07:00",
        relatedEntityIds: ["char_maya_pranata"],
        searchTerms: ["emergency", "emergency call", "north barrier", "call"],
        aliases: [],
        availabilityRule: { always: true },
        evidenceId: "ev_001_emergency_call",
        metadata: { call_time: "22:31", date: "2041-11-18", location: "North Barrier, Sector 7" },
      },
      {
        id: "rec_001_maya_profile",
        caseId: "case_001_missing_signal",
        recordType: "employee_record",
        title: "Maya Pranata — Employee Profile",
        body: {},
        source: { system: "pelaga_hr" },
        createdAt: "2041-11-18T21:45:00+07:00",
        relatedEntityIds: ["char_maya_pranata"],
        searchTerms: ["maya", "maya pranata", "employee", "profile", "engineer"],
        aliases: [],
        availabilityRule: { always: true },
        metadata: { last_check_in: "2041-11-18T21:45", department: "Flood Control Node 7" },
      },
      {
        id: "rec_001_sera_field_note",
        caseId: "case_001_missing_signal",
        recordType: "field_note",
        title: "CIAB Field Note — Sera Wibawa",
        body: {},
        source: { system: "ciab_field" },
        createdAt: "2041-11-19T08:00:00+07:00",
        relatedEntityIds: ["char_sera_wibawa", "char_maya_pranata"],
        searchTerms: ["sera", "sera wibawa", "field note", "ciab"],
        aliases: [],
        availabilityRule: { always: true },
        metadata: {},
      },
    ],
    evidence: [
      {
        id: "ev_001_ferry_departure",
        caseId: "case_001_missing_signal",
        title: "Ferry Departure Record",
        type: "database_record",
        summary: "A transit event claims Maya Pranata departed Nusakara at 22:14 on 2041-11-18.",
        source: { system: "ferry_archive" },
        occurredAt: "2041-11-18T22:14:00+07:00",
        tags: ["transit", "maya", "departure"],
        relatedEntityIds: ["char_maya_pranata"],
        assetIds: ["asset_001_ferry_document"],
        discoveryRule: { eventOccurred: { type: "record_opened", entityId: "rec_001_ferry_departure" } },
        optional: false,
        contested: true,
        redHerring: false,
        reportClaimsSupported: [],
      },
      {
        id: "ev_001_emergency_call",
        caseId: "case_001_missing_signal",
        title: "North Barrier Emergency Call Metadata",
        type: "system_log",
        summary:
          "An emergency call linked to Maya Pranata's device was logged at North Barrier at 22:31 on 2041-11-18.",
        source: { system: "emergency_dispatch" },
        occurredAt: "2041-11-18T22:31:00+07:00",
        tags: ["emergency", "maya", "north barrier"],
        relatedEntityIds: ["char_maya_pranata"],
        assetIds: ["asset_001_emergency_document"],
        discoveryRule: { eventOccurred: { type: "record_opened", entityId: "rec_001_emergency_call" } },
        optional: false,
        contested: false,
        redHerring: false,
        reportClaimsSupported: [],
      },
    ],
    hints: [
      {
        id: "hint_001_verify_location_1",
        objectiveId: "obj_001_verify_location",
        tier: 1,
        text: "Two records describe Maya's location on the same night. Compare the ferry archive with the emergency call metadata.",
      },
    ],
    dialogue: [
      {
        id: "dialogue_001_sera_intro",
        channelId: CASE_001_MAIL_CHANNEL_ID,
        speakerId: "char_sera_wibawa",
        text: "Pelaga Systems engineer Maya Pranata failed to report for a scheduled emergency maintenance review. Pelaga claims she voluntarily left the city after mishandling restricted data. Her transit account shows a ferry departure at 22:14. I am requesting verification because the departure record conflicts with an emergency call from the North Barrier logged at 22:31. Please verify Maya's final confirmed location.",
        enterRule: { always: true },
      },
    ],
    conclusions: [
      {
        id: "conclusion_001_missing_signal",
        caseId: "case_001_missing_signal",
        claimSlots: [],
        evidenceSlotCount: 3,
        disclosureChoices: [],
      },
    ],
    assets: [
      {
        id: "asset_maya_portrait",
        type: "image",
        sourcePath: "assets/case_001/maya-portrait.png",
        optimizedPath: "assets/case_001/maya-portrait.webp",
        license: "original",
        creator: "BLACKBOX team",
        provenanceNote: "Original placeholder portrait for Case 001 vertical slice.",
        caseIds: ["case_001_missing_signal"],
        preload: "none",
      },
      {
        id: "asset_sera_portrait",
        type: "image",
        sourcePath: "assets/case_001/sera-portrait.png",
        optimizedPath: "assets/case_001/sera-portrait.webp",
        license: "original",
        creator: "BLACKBOX team",
        provenanceNote: "Original placeholder portrait for Case 001 vertical slice.",
        caseIds: ["case_001_missing_signal"],
        preload: "none",
      },
      {
        id: "asset_001_ferry_document",
        type: "document",
        sourcePath: "assets/case_001/ferry-departure.png",
        optimizedPath: "assets/case_001/ferry-departure.webp",
        license: "original",
        creator: "BLACKBOX team",
        provenanceNote: "Original placeholder document for Case 001 vertical slice.",
        caseIds: ["case_001_missing_signal"],
        preload: "none",
      },
      {
        id: "asset_001_emergency_document",
        type: "document",
        sourcePath: "assets/case_001/emergency-call.png",
        optimizedPath: "assets/case_001/emergency-call.webp",
        license: "original",
        creator: "BLACKBOX team",
        provenanceNote: "Original placeholder document for Case 001 vertical slice.",
        caseIds: ["case_001_missing_signal"],
        preload: "none",
      },
    ],
    notifications: [],
  });

  if (!validateContentBundle(parsed).success) {
    throw new Error(`validateContentBundle failed for ${parsed.case.id}`);
  }

  return {
    content: parsed,
    initialState: stepCaseEngine(
      createInitialEngineState(),
      { kind: "game_event", event: { type: "case_001_bootstrap" } },
      parsed,
    ).state,
  };
}